### ISSUE TITLE
Sequences of vectors

### ISSUE THREAD

**Issue by kotrfa** [JonathanRaiman/theano_lstm#16]
Hello,

I have some sequence of vectors of the same length. Now I would like to train LSTM on train sample of this sequence and then make the network predict new sequence of vectors of the same length as input based on several *priming* vectors. 

I cannot find easily applicable example anywhere on the internet and I thought that your code could be suitable. Couldn't you please edit your example with words or add some new, which would done what I'm looking for?

Thank you

**Comment by JonathanRaiman** [comment]
Kotrfa, I'm not totally sure what you are asking for. In the example I have, I prime the network with a word embedding from the word "the". If you instead show your LSTM your input vector instead of a word embedding you will achieve what I think you wanted ?

**Comment by kotrfa** [comment]
Sorry for my ignorance - my knowledge about RNN isn't particularly good and hence my question. Now I understand.
