### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by mheilman** [JonathanRaiman/theano_lstm#7]
Hi, sorry to bother you, but I was wondering if you might put a license on the code.

(You're probably already aware of the following very useful site, but just in case: http://choosealicense.com/)

Thanks.

**Comment by nivwusquorum** [comment]
lol

**Comment by JonathanRaiman** [comment]
Very good idea. I'll read through a couple and get back to you on this. I think a general free to use, free to distribute license is good, and a disclaimer about responsibility. I'm open to suggestions.

**Comment by mheilman** [comment]
One possibility would be to use the same license as theano (BSD, see https://pypi.python.org/pypi/Theano or http://deeplearning.net/software/theano/LICENSE.html).  scikit-learn also uses that.

**Comment by JonathanRaiman** [comment]
Sounds like a good idea.
I just got my laptop stolen, so Ill need a few days to get around to this -- but if you want to push a LICENSE.md file to the repo I'll merge it from the web.

**Comment by mheilman** [comment]
#10 addresses this.  I just tweaked a copy of Theano's BSD license and put your name there, etc.  Please check it over.  Thanks.
